apiVersion: v1
kind: Pod
metadata:
  name: pod-pg-web
  namespace: pg-dev
  labels:
    category: pg-web
spec:
  containers:
  - name: container
    image: mgood2/pg-web
---
apiVersion: v1
kind: Service
metadata:
  name: svc-pg-web
  namespace: pg-dev
spec:
  selector:
    category: pg-web
  ports:
  - port: 3000
